services:
  app:
    build: .
    container_name: go-app
    mem_limit: 2048M
    mem_reservation: 1024M
    cpus: 1.5
    ports:
      - "8080:8080"
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    depends_on:
      - ffmpeg
      - redis

  ffmpeg:
    image: jrottenberg/ffmpeg:latest
    container_name: ffmpeg-container
    mem_limit: 1024M
    mem_reservation: 512M
    cpus: 2.0
    volumes:
      - .:/app

  redis:
    image: redis:7
    container_name: redis
    mem_limit: 512M
    mem_reservation: 256M
    cpus: 0.5
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
